### ISSUE TITLE
Failed to create ground station log - won't log this session

### ISSUE THREAD

**Issue by JamesMcFadden** [Eagle-Enterprises/C2#1]
This error is thrown when connecting to the mission planner on the Windows machine via remote desktop. The permissions for the logs folder was checked, and all users were shown as having full control permission. @Cybower @nickhubchak2

**Comment by Cybower** [comment]
The fix for this was running the Mission Planner software .exe as an administrator. This enabled mission planner to write to the log locations in its ProgramFiles path.
